import "./globals.css";

import Layout from "./component/layout/layout";
import ClientLoader from "./ClientLoader";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ClientLoader>



        <Layout>
          {children}
        </Layout>

        </ClientLoader>



      </body>
    </html>
  );
}
